### ISSUE TITLE
Error when returning from auth

### ISSUE THREAD

**Issue by chrisbenseler** [sabotatore/omniauth-untappd#2]
When the url "/auth/untappd/callback?code=XXXX" is being called, the following is happening. It didn't happen before, I guess it's something to do with Rails 4. Any clue?

Started GET "/auth/untappd/callback?code=4FC137EB7AE5AAFB504F76C50C84B9C258FF79CC" for 191.17.67.26 at 2015-02-07 15:52:59 +0000
F, [2015-02-07T15:52:59.368477 #1148] FATAL -- : 
TypeError (no implicit conversion of String into Integer):
  omniauth-untappd (0.1.1) lib/oauth2/untappd_client.rb:11:in `[]'
  omniauth-untappd (0.1.1) lib/oauth2/untappd_client.rb:11:in `parse_token'
  omniauth-untappd (0.1.1) lib/oauth2/untappd_client.rb:5:in `get_token'
  oauth2 (0.9.4) lib/oauth2/strategy/auth_code.rb:29:in `get_token'
  omniauth-oauth2 (1.1.2) lib/omniauth/strategies/oauth2.rb:93:in `build_access_token'
  omniauth-oauth2 (1.1.2) lib/omniauth/strategies/oauth2.rb:75:in `callback_phase'

**Comment by tauil** [comment]
@chrisbenseler Are you still getting this error? I've just [fixed an issue with HTTPS](https://github.com/sabotatore/omniauth-untappd/pull/3)

Everything is working fine to me right now.

**Comment by sabotatore** [comment]
fixed in 0.1.3 version
